# pocaml configuration -*- Makefile -*-
# $Id: Makefile.config,v 1.25 2005/03/31 13:46:31 rich Exp $

# PERLINCDIR
# Directory containing the Perl include files, eg. <EXTERN.h>.

PERLINCDIR := $(shell perl -MConfig -e 'print "$$Config{archlib}/CORE"')

# OCAMLLIBDIR
# This is where we will install pocaml (actually in the /perl subdirectory
# of this, so you will need to add '-I +perl' when compiling programs).

OCAMLLIBDIR := $(shell ocamlc -where)

# EXTRA_CFLAGS
# You can specify extra flags to be passed to gcc here.
#
# One flag you might want to pass here is
#
#   -DPERL4CAML_REFCOUNTING_EXPERIMENTAL=1
#
# which will turn on experimental support for reference counting.
# Without this none of the Perl structures that you allocate will get
# freed.  With this we try to map Perl's reference counting onto
# OCaml's garbage collection by using finalizers.  Although the
# feature is marked "EXPERIMENTAL", I have fixed most of the bugs
# and it's now turned on by default.

EXTRA_CFLAGS := -DPERL4CAML_REFCOUNTING_EXPERIMENTAL=1

# DYNALOADER_HACK
# XXX Hack required by ocamlopt, and sometimes ocamlc.
# To work out what this should be, try:
# `perl -MExtUtils::Embed -e ldopts'

DYNALOADER_HACK := /System/Library/Perl/5.8.6/darwin-thread-multi-2level/auto/DynaLoader/DynaLoader.a

# PACKAGE and VERSION

PACKAGE := pocaml
VERSION := 0.0.1
